In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_parquet("audio_shards/train_001.parquet")

In [4]:
df.head()

,id,audio,cleaned_text,cleaned_text_lowercase
0,0,b'RIFF$\x9c\x06\x00WAVEfmt \x10\x00\x00\x00\x0...,Isbilermenlik subektleri ushın xabardar etiw t...,isbilermenlik subektleri ushın xabardar etiw t...
1,1,b'RIFF\xd06\x07\x00WAVEfmt \x10\x00\x00\x00\x0...,Bul jol arqalı Shımbay tek ǵana ishki ekonomik...,bul jol arqalı shımbay tek ǵana ishki ekonomik...
2,2,b'RIFF\x80\x9c\x08\x00WAVEfmt \x10\x00\x00\x00...,Tutınıw sebetindegi ónim hám xızmetlerdiń jetp...,tutınıw sebetindegi ónim hám xızmetlerdiń jetp...
3,3,b'RIFFz\xfd\x08\x00WAVEfmt \x10\x00\x00\x00\x0...,Jergilikli qatnasıwshılar ushın kórgizbeniń ek...,jergilikli qatnasıwshılar ushın kórgizbeniń ek...
4,4,b'RIFF* \x07\x00WAVEfmt \x10\x00\x00\x00\x01\x...,Sessiyanıń kún tártibindegi dáslepki másele «Q...,sessiyanıń kún tártibindegi dáslepki másele qa...

In [5]:
dt=pd.read_parquet("data/test_metadata.parquet")

In [6]:
dt.head()

,id,cleaned_text_lowercase,source_file,source_row
0,2432,paytaxtımızdıń kongressorayında mámleketimiz b...,train_003.parquet,428
1,6655,sanlı texnologiyalar baǵdarındaǵı ózara sóyles...,train_007.parquet,639
2,16365,jaslar hawazı festivalınıń ashılıw saltanatı b...,train_017.parquet,320
3,2307,sonıń menen birge ayırım máselelerdi tereńirek...,train_003.parquet,304
4,18829,sońǵı jıllarda bilimlendiriw tarawında ámelge ...,train_019.parquet,772